server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: mybatis-plus-demo
  datasource:
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j2
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    master:
      url: jdbc:mysql://localhost:3306/test1?useUnicode=true&useSSL=false&characterEncoding=utf8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slaver:
      url: jdbc:mysql://localhost:3306/test2?useUnicode=true&useSSL=false&characterEncoding=utf8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  # jackson时间格式化
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss